# Generated by Django 4.1.7 on 2023-02-23 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Epiciers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='client',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Credit',
        ),
    ]
