# Generated by Django 4.1.7 on 2023-02-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Epiciers', '0002_delete_article_remove_credit_client_delete_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
                ('telephone', models.CharField(max_length=200, null=True)),
                ('dateCreation', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
