# Generated by Django 4.1.7 on 2023-02-23 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Epiciers', '0004_remove_client_datecreation_client_adresse_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='client',
        ),
    ]
