# Generated by Django 4.1.7 on 2023-02-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Epiciers', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='montant_de_credit',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='montant_à_payer',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.IntegerField(max_length=10),
        ),
    ]
