# Generated by Django 4.1.7 on 2023-02-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Epiciers', '0008_produit_alter_client_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='quantité_vendues',
            field=models.FloatField(null=True),
        ),
    ]
